version: '3.8'

services:

  odoo:
    image: odoo:17.0
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=intel_internship_ppwwwdd
    volumes:
      - odoo-data:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons
      - ./odoo_conf:/etc/odoo

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: intel_internship_ppwwwdd
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
    test:
      image: medlas/odoo:${DOCKER_TAG}
      container_name: odoo_test
      volumes:
        - .:/mnt/extra-addons
      command: python3 /mnt/extra-addons/test.py
      depends_on:
        - odoo
        - db

volumes:
  odoo-data:
  postgres-data: