services:
  odoo:
    image: medlas/odoo:${DOCKER_TAG}
    container_name: odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  odoo_data:
  postgres_data:
