version: '3.8'

services:
  odoo:
    image: odoo:latest
    container_name: odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  odoo_data:
  postgres_data:
